# Generated by Django 5.2.4 on 2025-12-13 16:49

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job title or position name (e.g., 'Senior Python Developer')", max_length=255)),
                ('company', models.CharField(blank=True, help_text='Company or organization name', max_length=255)),
                ('text', models.TextField(help_text='Full job description including responsibilities and requirements')),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='Mandatory skills required for the position')),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text='Nice-to-have skills that are not mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this job description was created')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this job description', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Uploaded offer letter file (PDF/DOCX)', null=True, upload_to=core.models.offer_letter_file_path)),
                ('text', models.TextField(blank=True, help_text='Full text content of the offer letter')),
                ('explanation', models.TextField(blank=True, help_text='Detailed AI analysis explaining the offer terms')),
                ('risk_flags', models.JSONField(blank=True, default=list, help_text='Problematic clauses or concerning terms found')),
                ('ctc', models.CharField(blank=True, help_text='Cost to Company - total annual compensation', max_length=100)),
                ('probation_period', models.CharField(blank=True, help_text='Duration of probation period', max_length=100)),
                ('notice_period', models.CharField(blank=True, help_text='Required notice period for resignation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this offer was analyzed')),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded this offer letter', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Letter',
                'verbose_name_plural': 'Offer Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Uploaded resume file (PDF/DOCX/TXT)', null=True, upload_to=core.models.resume_file_path)),
                ('parsed_text', models.TextField(blank=True, help_text='Full text extracted from resume for processing')),
                ('extracted_skills', models.JSONField(blank=True, default=list, help_text="Skills extracted from resume (e.g., ['Python', 'Django', 'SQL'])")),
                ('education', models.JSONField(blank=True, default=list, help_text='Education history with degrees, institutions, and years')),
                ('experience', models.JSONField(blank=True, default=list, help_text='Work history with companies, positions, and durations')),
                ('name', models.CharField(blank=True, help_text="Candidate's full name", max_length=255)),
                ('email', models.EmailField(blank=True, help_text="Candidate's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Candidate's phone number", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this resume was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this resume was last modified')),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded this resume', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField(help_text='Complete cover letter text generated by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cover letter was generated')),
                ('job_description', models.ForeignKey(help_text='Job description for this application', on_delete=django.db.models.deletion.CASCADE, to='core.jobdescription')),
                ('resume', models.ForeignKey(help_text='Resume used to generate this cover letter', on_delete=django.db.models.deletion.CASCADE, to='core.resume')),
            ],
            options={
                'verbose_name': 'Cover Letter',
                'verbose_name_plural': 'Cover Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage match between resume and job (0-100)', max_digits=5)),
                ('missing_skills', models.JSONField(blank=True, default=list, help_text='Skills required by job but missing from resume')),
                ('matching_skills', models.JSONField(blank=True, default=list, help_text='Skills that match between resume and job')),
                ('suggested_resources', models.JSONField(blank=True, default=list, help_text='Recommended courses or resources to learn missing skills')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this analysis was performed')),
                ('job_description', models.ForeignKey(help_text='Job description for skill comparison', on_delete=django.db.models.deletion.CASCADE, to='core.jobdescription')),
                ('resume', models.ForeignKey(help_text='Resume being matched against job', on_delete=django.db.models.deletion.CASCADE, to='core.resume')),
            ],
            options={
                'verbose_name': 'Skill Gap Report',
                'verbose_name_plural': 'Skill Gap Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
