# Generated by Django 5.2.4 on 2025-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('course', 'Course'), ('book', 'Book'), ('docs', 'Documentation'), ('video', 'Video'), ('certification', 'Certification'), ('guide', 'Guide')], max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="e.g., '10-15 hours'", max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority resources shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'skill', 'title'],
                'indexes': [models.Index(fields=['skill', 'is_active'], name='core_learni_skill_606933_idx')],
            },
        ),
    ]
