# Generated by Django 5.2.4 on 2025-12-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='coverletter',
            name='generated_text',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Generated cover letter content'),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Custom instructions provided by user', null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(blank=True, default='full-time', help_text='Employment type (full-time, part-time, contract)', max_length=50),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, default='Not specified', help_text='Job location', max_length=255),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='salary_range',
            field=models.CharField(blank=True, default='', help_text='Salary range', max_length=100),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='job_description',
            field=models.ForeignKey(blank=True, help_text='Job description this cover letter is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobdescription'),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='resume',
            field=models.ForeignKey(help_text='Resume this cover letter is based on', on_delete=django.db.models.deletion.CASCADE, to='core.resume'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list, help_text='Nice-to-have skills'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='Mandatory skills required'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(help_text='Job title or position name', max_length=255),
        ),
    ]
